package com.mikeywestman.agentflow.execution;

import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Service;

@Service
@Order(3)
public class StubAiProvider implements AiProvider {

    @Override
    public AiGenerationResult generate(String systemPrompt, String userPrompt) {
        String output = "[Stub AI Output]\n\nInstructions:\n" + systemPrompt + "\n\nInput:\n" + userPrompt + "\n\nThis response was generated by the local stub provider.";
        return new AiGenerationResult(output, providerName(), modelName());
    }

    @Override
    public String providerName() {
        return "Stub";
    }

    @Override
    public String modelName() {
        return "local-stub";
    }
}
